Week3 : 전민주 스터디 필기, 과제 1 제출
KGU-C-Lab/C-Lab_23-2_AndroidStudy pull request #19
Opened 2023-10-15 04:37 UTC by mingmingmon

Week3 : 전민주 스터디 필기, 과제 1 제출

2023-10-15 04:37 UTC, mingmingmon commented
Week3 : 전민주 스터디 필기, 과제 1 제출

2023-10-15 06:26 UTC, mingmingmon commented
Week3 : 전민주 과제2 제출

2023-10-15 06:28 UTC, mingmingmon commented
Week3 : 전민주 과제2 제출

2023-10-23 11:29 UTC, chattymin requested changes
이번 한주 고생하셨습니당 :)

2023-10-23 11:29 UTC, chattymin commented on 전민주/Week 3/HW_1/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintHorizontal_bias="0.5"
이 코드는 결과물에 영향을 주지 않기때문에 삭제하는게 좋을 것 같습니당

2023-10-23 11:29 UTC, chattymin commented on 전민주/Week 3/HW_1/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintTop_toBottomOf="@+id/editMBTI" />
@id와 @+id의 차이점은 조금 큽니다!
@+id는 새로 생성하는 것을 의미하기 때문에 @id로 코드 수정해주세용

2023-10-23 11:29 UTC, chattymin commented on 전민주/Week 3/HW_2/app/src/main/java/com/mingmingmon/week3_hw_2/MainActivity.kt
> +        }
토스트를 함수로 만든것 정말 좋은거 같습니다!!
근데 두 함수의 차이점이 내부 text라면, text를 변수로 받아오게 할 경우 하나로 줄일 수 있을 것 같네용

2023-10-23 11:29 UTC, chattymin commented on 전민주/Week 3/HW_2/app/src/main/java/com/mingmingmon/week3_hw_2/MainActivity.kt
> +            }
이 부분도 중복이 많이 발생하는데 함수화 하면 더 좋을 것 같습니다!!
물론 지금도 정말 좋아요 :)

2023-10-30 09:17 UTC, mingmingmon commented
week3 전민주 과제 refactor

2023-10-30 15:33 UTC, chattymin approved these changes
완벽한 코드네요!! 너무 잘한다....

2023-10-30 15:33 UTC, chattymin commented on 전민주/Week 3/HW_2/app/src/main/java/com/mingmingmon/week3_hw_2/MainActivity.kt
> +            //String으로 상황에 맞는 경고 메세지를 받아서 띄우도록 수정했습니다.
재사용성 굿!!

2023-10-30 15:33 UTC, chattymin commented on 전민주/Week 3/HW_2/app/src/main/java/com/mingmingmon/week3_hw_2/MainActivity.kt
> +            val result: Int?
null 체크는 왜 한걸까요??

2023-10-30 15:33 UTC, merged