Week 3: 권시훈 Pull Request
KGU-C-Lab/C-Lab_23-2_AndroidStudy pull request #21
Opened 2023-10-16 05:23 UTC by kanai1

Feat: 스터디 실습 코드
Feat: 과제

2023-10-23 11:16 UTC, chattymin requested changes
이번주도 고생하셨습니다 :)

2023-10-23 11:16 UTC, chattymin commented on 권시훈/Week 3/과제/Calculator/app/src/main/java/com/kanai1/calculator/MainActivity.kt
> +            if(binding.input1.text.toString() == "" || binding.input2.text.toString() == "") {
내장함수를 활용하는 것도 좋은 방법일 것 같습니다.
그리고 내부에 공백이 들어있는 경우에도 에러가 발생할 것 같은데 이것도 고려하면 좋을 것 같네요
" "

2023-10-23 11:16 UTC, chattymin commented on 권시훈/Week 3/과제/Calculator/app/src/main/java/com/kanai1/calculator/MainActivity.kt
> +                binding.result.text = "Result: -"
이 내용은 대부분의 버튼 클릭시 중복되는데 함수화하면 좋을 것 같습니다!!

2023-10-23 11:16 UTC, chattymin commented on 권시훈/Week 3/과제/signup/app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintStart_toStartOf="@+id/editTextID" />
코드가 깔끔하고 좋네요!
그런데 ui상의 순서대로 있으면 가독성 측면에서 더 좋을 것 같습니다.ㅣ
그리고 변수 명이 조금 더 명확했으면 좋을 것 같네요

2023-10-24 05:13 UTC, kanai1 commented
수정사항들 전부 확인 및 수정하고 Commit했습니다!

2023-10-24 08:19 UTC, chattymin approved these changes
깔끔한 코드 잘 봤습니다!!
아주그냥 야무져요~ :)

2023-10-30 15:33 UTC, merged